version: 2.1

workflows:
  build:
    jobs:
      - test:
          version: 10-stretch
      - test:
          version: lts-stretch
      - test:
          version: current-stretch

jobs:
  test:
    parameters:
      version:
        type: string

    docker:
      - image: circleci/node:<< parameters.version >>

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm ci
      - run: npm t
      - run: |
          if [ "$CIRCLE_BRANCH" == "master" ] && [ "$CIRCLE_STAGE" == "test-3" ]; then
                echo "Running nlm release";
                npx nlm release;
          else
                echo "Not running nlm release!";
          fi
