name: Dependency Review

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    name: Review Dependencies
    steps:
      - name: Check out the source code
        uses: actions/checkout@v5

      - name: Review dependencies
        uses: actions/dependency-review-action@v4.8.0
        with:
          comment-summary-in-pr: true
          show-openssf-scorecard: true
          vulnerability-check: true
