---
name: Prepare new npm release

on:
  workflow_dispatch:
    inputs:
      npm-version-type:
        description: 'The npm version type we are publishing.'
        required: true
        type: choice
        default: 'patch'
        options:
          - patch
          - minor
          - major

permissions:
  contents: read

jobs:
  prepare:
    name: Prepare a new npm release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out the source code
        uses: actions/checkout@v6

      - name: Run npm-prepare-release
        uses: Automattic/vip-actions/npm-prepare-release@c8022b66e78461df4f802b935dc0dbb8399f96bc # v0.7.4
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          npm-version-type: ${{ inputs.npm-version-type }}
          conventional-commits: 'true'
